apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
    # created this secret using kubectl create secret docker-registry acr-secret
      # imagePullSecrets:
      # - name: acr-secret    
      containers:
        - name: node-app
          # image: surajpatil7438/node-api:latest
          image: acrdevopsprojectswithterraform.azurecr.io/node-api:1.1
          ports:
            - containerPort: 3000
